# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'

jobs:
  testnbump:
    name: Test on node ${{matrix.node_version}} and on ${{matrix.os}} then bump the version number
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        node_version: [18.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Use latest Node.js version ${{matrix.node_version}}
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node_version}}
    
      - name: npm install and test
        run: |
          npm install
          npm ci
          npm run test --if-present
      
      - name: bump version then publish
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          node bump-v.js
          git commit -m 'auto bump' -a
          git push https://github.com/Krorenshima/Utonmae.git
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
